export const ROUTES = {
  home: '/',
  guestBook: '/book',
  services: '/services',
  packages: '/packages',
  bridalPackages: '/packages/bridal',
  groomPackages: '/packages/groom',
  destinationPackage: '/packages/destination',
  invoice: (id = ':id') => `/invoice/${id}`,
  about: '/about',
  gallery: '/gallery',
  contact: '/contact',

  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',

  customerDashboard: '/dashboard',
  myAppointments: '/dashboard/appointments',
  book: '/dashboard/book',
  profile: '/dashboard/profile',

  admin: '/admin',
  adminServices: '/admin/services',
  adminPackages: '/admin/packages',
  adminHolidays: '/admin/holidays',
  adminStaff: '/admin/staff',
  adminAppointments: '/admin/appointments',
  adminCustomers: '/admin/customers',
  adminCustomerProfile: (id = ':id') => `/admin/customers/${id}`,
  adminInventory: '/admin/inventory',
  adminBilling: '/admin/billing',
  adminSales: '/admin/sales',
  adminReports: '/admin/reports',
  adminSettings: '/admin/settings',
  adminBook: '/admin/book',
  adminCoupons: '/admin/coupons',
  adminCouponDesign: '/admin/coupons/design',
  adminProfile: '/admin/profile',

  staff: '/staff',
  staffSchedule: '/staff/schedule',
  staffAppointments: '/staff/appointments',
  staffBilling: '/staff/billing',
  staffSales: '/staff/sales',
  staffBook: '/staff/book',
  staffProfile: '/staff/profile',
} as const;
