import type { Appointment, Product, Review, Service, Staff, User } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Priya Sharma',
    email: 'customer@salon.com',
    phone: '+91 98765 43210',
    role: 'customer',
    avatarUrl: 'https://i.pravatar.cc/150?img=47',
    createdAt: '2025-03-14',
  },
  {
    id: 'u2',
    name: 'Rahul Verma',
    email: 'staff@salon.com',
    phone: '+91 98111 22233',
    role: 'staff',
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    createdAt: '2024-08-01',
  },
  {
    id: 'u3',
    name: 'Anjali Kapoor',
    email: 'admin@salon.com',
    phone: '+91 90000 00001',
    role: 'admin',
    avatarUrl: 'https://i.pravatar.cc/150?img=32',
    createdAt: '2023-01-10',
  },
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 's1',
    name: 'Signature Haircut & Style',
    description: 'Personalized haircut with wash, blow-dry and styling.',
    category: 'hair',
    gender: 'unisex',
    priceInr: 799,
    durationMinutes: 45,
    imageUrl:
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's2',
    name: 'Global Hair Colour',
    description: 'Ammonia-free global colour with deep conditioning.',
    category: 'hair',
    gender: 'unisex',
    priceInr: 3499,
    durationMinutes: 120,
    imageUrl:
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's3',
    name: 'Keratin Smoothening',
    description: 'Frizz control with long-lasting shine and smoothness.',
    category: 'hair',
    gender: 'female',
    priceInr: 5499,
    durationMinutes: 180,
    imageUrl:
      'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's4',
    name: 'Classic Facial',
    description: 'Deep-cleansing facial for glowing, refreshed skin.',
    category: 'skin',
    gender: 'unisex',
    priceInr: 1299,
    durationMinutes: 60,
    imageUrl:
      'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's5',
    name: 'Anti-Aging Facial',
    description: 'Premium collagen-boosting facial with LED therapy.',
    category: 'skin',
    gender: 'unisex',
    priceInr: 2499,
    durationMinutes: 75,
    imageUrl:
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's6',
    name: 'Gel Manicure',
    description: 'Long-lasting gel polish with premium nail prep.',
    category: 'nails',
    gender: 'female',
    priceInr: 899,
    durationMinutes: 45,
    imageUrl:
      'https://images.unsplash.com/photo-1610992015732-2449b76344bc?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's7',
    name: 'Spa Pedicure',
    description: 'Relaxing pedicure with foot massage and mask.',
    category: 'nails',
    gender: 'unisex',
    priceInr: 999,
    durationMinutes: 50,
    imageUrl:
      'https://images.unsplash.com/photo-1519415943484-9fa1873496d4?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's8',
    name: 'Bridal Makeup',
    description: 'HD airbrush bridal makeup with trial session.',
    category: 'makeup',
    gender: 'female',
    priceInr: 12999,
    durationMinutes: 150,
    imageUrl:
      'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's9',
    name: 'Party Makeup',
    description: 'Glam party-ready makeup with lashes.',
    category: 'makeup',
    gender: 'female',
    priceInr: 2499,
    durationMinutes: 60,
    imageUrl:
      'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's10',
    name: 'Aromatherapy Massage',
    description: '60-min full-body relaxation massage with essential oils.',
    category: 'spa',
    gender: 'unisex',
    priceInr: 2299,
    durationMinutes: 60,
    imageUrl:
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's11',
    name: "Men's Beard Grooming",
    description: 'Beard shaping, trim, and hot-towel treatment.',
    category: 'grooming',
    gender: 'male',
    priceInr: 499,
    durationMinutes: 30,
    imageUrl:
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
  {
    id: 's12',
    name: "Men's Head Massage",
    description: 'Deep tissue head massage with premium oils.',
    category: 'spa',
    gender: 'male',
    priceInr: 799,
    durationMinutes: 30,
    imageUrl:
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=800&auto=format&fit=crop&q=60',
    isActive: true,
  },
];

export const MOCK_STAFF: Staff[] = [
  {
    id: 'st1',
    name: 'Rahul Verma',
    role: 'Senior Hair Stylist',
    bio: '10+ years crafting cuts inspired by international runways.',
    specialties: ['hair', 'grooming'],
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    rating: 4.9,
    experienceYears: 10,
    isActive: true,
  },
  {
    id: 'st2',
    name: 'Sneha Iyer',
    role: 'Skin & Facial Expert',
    bio: 'Certified aesthetician specializing in advanced skin therapies.',
    specialties: ['skin', 'spa'],
    avatarUrl: 'https://i.pravatar.cc/150?img=25',
    rating: 4.8,
    experienceYears: 7,
    isActive: true,
  },
  {
    id: 'st3',
    name: 'Meera Nair',
    role: 'Nail Artist',
    bio: 'Award-winning nail artist. Loves intricate gel designs.',
    specialties: ['nails'],
    avatarUrl: 'https://i.pravatar.cc/150?img=48',
    rating: 4.9,
    experienceYears: 5,
    isActive: true,
  },
  {
    id: 'st4',
    name: 'Aisha Khan',
    role: 'Bridal Makeup Artist',
    bio: 'Trusted by 500+ brides for HD & airbrush makeup.',
    specialties: ['makeup'],
    avatarUrl: 'https://i.pravatar.cc/150?img=44',
    rating: 5.0,
    experienceYears: 8,
    isActive: true,
  },
  {
    id: 'st5',
    name: 'Karan Malhotra',
    role: 'Master Barber',
    bio: "Precision men's cuts, fades, and beard sculpting.",
    specialties: ['hair', 'grooming'],
    avatarUrl: 'https://i.pravatar.cc/150?img=15',
    rating: 4.7,
    experienceYears: 12,
    isActive: true,
  },
  {
    id: 'st6',
    name: 'Divya Rao',
    role: 'Spa Therapist',
    bio: 'Balinese & Swedish massage certified.',
    specialties: ['spa'],
    avatarUrl: 'https://i.pravatar.cc/150?img=36',
    rating: 4.8,
    experienceYears: 6,
    isActive: true,
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1',
    customerId: 'u1',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98765 43210',
    staffId: 'st1',
    staffName: 'Rahul Verma',
    serviceIds: ['s1'],
    serviceNames: ['Signature Haircut & Style'],
    date: '2026-07-25',
    startTime: '11:00',
    endTime: '11:45',
    status: 'confirmed',
    totalInr: 799,
    notes: 'Prefers shoulder length',
    createdAt: '2026-07-18',
  },
  {
    id: 'a2',
    customerId: 'u1',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98765 43210',
    staffId: 'st2',
    staffName: 'Sneha Iyer',
    serviceIds: ['s4', 's6'],
    serviceNames: ['Classic Facial', 'Gel Manicure'],
    date: '2026-08-02',
    startTime: '14:00',
    endTime: '15:45',
    status: 'pending',
    totalInr: 2198,
    createdAt: '2026-07-19',
  },
  {
    id: 'a3',
    customerId: 'u1',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98765 43210',
    staffId: 'st3',
    staffName: 'Meera Nair',
    serviceIds: ['s7'],
    serviceNames: ['Spa Pedicure'],
    date: '2026-06-10',
    startTime: '17:00',
    endTime: '17:50',
    status: 'completed',
    totalInr: 999,
    createdAt: '2026-06-05',
  },
  {
    id: 'a4',
    customerId: 'u4',
    customerName: 'Aditya Rao',
    customerPhone: '+91 99887 66554',
    staffId: 'st5',
    staffName: 'Karan Malhotra',
    serviceIds: ['s11'],
    serviceNames: ["Men's Beard Grooming"],
    date: '2026-07-21',
    startTime: '10:00',
    endTime: '10:30',
    status: 'confirmed',
    totalInr: 499,
    createdAt: '2026-07-20',
  },
  {
    id: 'a5',
    customerId: 'u5',
    customerName: 'Neha Bansal',
    customerPhone: '+91 98123 45678',
    staffId: 'st4',
    staffName: 'Aisha Khan',
    serviceIds: ['s8'],
    serviceNames: ['Bridal Makeup'],
    date: '2026-07-21',
    startTime: '09:00',
    endTime: '11:30',
    status: 'in_progress',
    totalInr: 12999,
    createdAt: '2026-07-01',
  },
  {
    id: 'a6',
    customerId: 'u6',
    customerName: 'Rohit Sinha',
    customerPhone: '+91 98999 11223',
    staffId: 'st6',
    staffName: 'Divya Rao',
    serviceIds: ['s10'],
    serviceNames: ['Aromatherapy Massage'],
    date: '2026-07-22',
    startTime: '18:00',
    endTime: '19:00',
    status: 'pending',
    totalInr: 2299,
    createdAt: '2026-07-20',
  },
  {
    id: 'a7',
    customerId: 'u7',
    customerName: 'Kavya Menon',
    customerPhone: '+91 90101 20202',
    staffId: 'st2',
    staffName: 'Sneha Iyer',
    serviceIds: ['s5'],
    serviceNames: ['Anti-Aging Facial'],
    date: '2026-05-14',
    startTime: '15:00',
    endTime: '16:15',
    status: 'cancelled',
    totalInr: 2499,
    createdAt: '2026-05-10',
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    customerId: 'u1',
    customerName: 'Priya Sharma',
    customerAvatar: 'https://i.pravatar.cc/150?img=47',
    staffId: 'st1',
    rating: 5,
    comment: 'Absolutely loved the haircut Rahul gave me. Best salon experience ever!',
    createdAt: '2026-06-11',
  },
  {
    id: 'r2',
    customerId: 'u4',
    customerName: 'Aditya Rao',
    customerAvatar: 'https://i.pravatar.cc/150?img=54',
    staffId: 'st5',
    rating: 5,
    comment: "Karan's beard sculpting is unmatched. Highly recommend.",
    createdAt: '2026-05-30',
  },
  {
    id: 'r3',
    customerId: 'u5',
    customerName: 'Neha Bansal',
    customerAvatar: 'https://i.pravatar.cc/150?img=41',
    staffId: 'st4',
    rating: 5,
    comment: 'Aisha made me look magical for my wedding. Forever grateful.',
    createdAt: '2026-04-22',
  },
  {
    id: 'r4',
    customerId: 'u6',
    customerName: 'Rohit Sinha',
    customerAvatar: 'https://i.pravatar.cc/150?img=59',
    staffId: 'st6',
    rating: 4,
    comment: 'The aromatherapy massage was blissful.',
    createdAt: '2026-03-15',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Argan Oil Shampoo',
    brand: 'Moroccan Luxe',
    category: 'Hair Care',
    stock: 42,
    priceInr: 899,
    reorderLevel: 15,
  },
  {
    id: 'p2',
    name: 'Vitamin C Serum',
    brand: 'GlowLab',
    category: 'Skin Care',
    stock: 8,
    priceInr: 1499,
    reorderLevel: 10,
  },
  {
    id: 'p3',
    name: 'Gel Polish (Rose Nude)',
    brand: 'NailArtPro',
    category: 'Nails',
    stock: 3,
    priceInr: 599,
    reorderLevel: 8,
  },
  {
    id: 'p4',
    name: 'Beard Balm',
    brand: 'GentsCraft',
    category: 'Grooming',
    stock: 26,
    priceInr: 449,
    reorderLevel: 12,
  },
  {
    id: 'p5',
    name: 'Aromatherapy Oil Set',
    brand: 'Serenity',
    category: 'Spa',
    stock: 14,
    priceInr: 1299,
    reorderLevel: 10,
  },
];

export const TIME_SLOTS = [
  '09:00',
  '09:30',
  '10:00',
  '10:30',
  '11:00',
  '11:30',
  '12:00',
  '12:30',
  '13:00',
  '13:30',
  '14:00',
  '14:30',
  '15:00',
  '15:30',
  '16:00',
  '16:30',
  '17:00',
  '17:30',
  '18:00',
  '18:30',
  '19:00',
];

export const CATEGORY_LABELS: Record<string, string> = {
  hair: 'Hair',
  skin: 'Skin & Facial',
  nails: 'Nails',
  makeup: 'Makeup',
  spa: 'Spa & Massage',
  grooming: 'Grooming',
};

export const SALON_INFO = {
  name: 'The Beauty Town',
  tagline: 'Your beauty, our craft.',
  address:
    'First Floor, Vidhi Square Complex, Near Govardhan Nathji Haveli, B.P.C. Road, Alkapuri, Vadodara, Gujarat 390007',
  phone: '+91 91578 19391',
  email: 'Payalshah1814@gmail.com',
  gstin: '',
  hours: 'Mon–Sun · 10:00 AM – 9:00 PM',
  socials: {
    instagram: 'https://instagram.com/thebeautytown',
    facebook: 'https://facebook.com/thebeautytown',
  },
};

// Salon ambience/work photos — shared by GalleryPage's full grid and
// HomePage's gallery preview strip so there's one list to update.
export const GALLERY_IMAGES = [
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1600948836101-f9ffda59d250?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1610992015732-2449b76344bc?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1519415943484-9fa1873496d4?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&auto=format&fit=crop&q=60',
  'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=60',
];
